# coding: utf-8
a = "Ola! tudo bem?"
b = "Para começarmos digite o seu nome"
c = "Qual o seu nome?"
d = "Bem vindo ao Nubank"
f = "Hoje você poderar explorar algumas salas de reunião da aqui do Nubank"
g = "Vamos lá"
h = """Em qual sala você quer entrar?
1 - Dino
2 - WOW
3 - Sauna"""
i = ""
j = ""
k = ""
l = "Você deseja fazer alguma coisa com isso?"
m = "Desculpe, mas isso é so uma visita depois faremos algo com isso"
n = "Tem certeza?"
o = "Isso não pode"
p = "Essa é a nossa TV nova"
q = "As vezes essa sala pode atrair um dog"
r = "A muitas coisas aqui :)"
s = "O quadro esta cheio de sujeira, voce me ajuda limpar?"
t = "Sim"
u = "Nao"
v = "Faça um carinho no Lost"
w = ":)"
x = "Obrigado"
y = "sair"
z = "Obrigado por vir visitar o Nubank"